<script setup>
import { computed, ref } from 'vue'
import { LayoutDashboard, FolderKanban, ClipboardList, Plane, ScanSearch, ShieldCheck, GitCompare, FileText, Bell, Search, ChevronDown, Plus, Upload, Check, X, RotateCcw, MapPin, CalendarDays, Clock3, ArrowUpRight, Menu, UserRound, Settings2, CloudUpload, Sparkles, History, PackageCheck, Send, Eye } from 'lucide-vue-next'

const loggedIn = ref(false)
const active = ref('dashboard')
const detailProject = ref(false)
const showNewProject = ref(false)
const showAddIssue = ref(false)
const uploadDone = ref(false)
const toast = ref('')
const query = ref('')
const issueFilter = ref('全部')
const roleKey = ref('manager')
const showRoleMenu = ref(false)
const showProjectDetail = ref(false)
const showTaskDetail = ref(false)
const selectedProjectId = ref('PRJ-HDN-001')
const selectedTaskId = ref('TASK-20260812-001')
const reportStatus = ref('待负责人审核')
const logs = ref([
  {time:'2026-08-12 11:20',role:'检查人员',text:'完成影像归档校验，任务进入待AI分析'},
  {time:'2026-08-12 10:05',role:'无人机飞手',text:'上传28份现场资料（照片、视频、飞行记录）'},
  {time:'2026-08-12 09:00',role:'调度人员',text:'确认张伟 / DJI Mavic 3E执行任务'},
  {time:'2026-08-11 16:30',role:'项目负责人',text:'由月度巡检计划生成任务'},
])
const roles = {
  manager:{label:'项目负责人',short:'负',desc:'项目交付与报告审核'},
  dispatcher:{label:'调度人员',short:'调',desc:'任务排班与资源调度'},
  pilot:{label:'无人机飞手',short:'飞',desc:'现场执行与资料上传'},
  inspector:{label:'检查人员',short:'检',desc:'影像复核与问题审核'},
  admin:{label:'系统管理员',short:'管',desc:'账号、权限与审计'},
}
const currentRole = computed(()=>roles[roleKey.value])

const nav = [
  { key:'dashboard', label:'巡检工作台', icon:LayoutDashboard, roles:Object.keys(roles) },
  { key:'projects', label:'项目与区域', icon:FolderKanban, roles:['manager','dispatcher','inspector','admin'] },
  { key:'tasks', label:'任务调度', icon:ClipboardList, roles:['manager','dispatcher','pilot','inspector','admin'] },
  { key:'fleet', label:'飞手与设备', icon:Plane },
  { key:'ai', label:'AI影像分析', icon:ScanSearch, badge:'辅助', roles:['manager','pilot','inspector','admin'] },
  { key:'issues', label:'问题审核', icon:ShieldCheck, roles:['manager','inspector','admin'] },
  { key:'history', label:'历史对比', icon:GitCompare, roles:['manager','inspector','admin'] },
  { key:'reports', label:'报告交付', icon:FileText, roles:['manager','inspector','admin'] },
]
nav[3].roles=['manager','dispatcher','admin']
const visibleNav = computed(()=>nav.filter(item=>item.roles.includes(roleKey.value)))
const projects = ref([
  {id:'PRJ-HDN-001', name:'华东新能源科技园一期', client:'华东新能源科技有限公司', area:'A区 / 组件区01-08', cycle:'月度巡检', status:'执行中', manager:'李晨', progress:72, date:'2026-08-12', regions:8, standard:'光伏组件外观与热成像检查', plan:'2026年8月月度巡检计划'},
  {id:'PRJ-SZ-002', name:'苏州工业园区屋顶光伏', client:'苏州工业园区发展集团', area:'5号厂房 / 屋顶', cycle:'季度巡检', status:'待执行', manager:'王欣', progress:18, date:'2026-08-18', regions:3, standard:'屋面组件与排水检查', plan:'2026年第三季度巡检计划'},
  {id:'PRJ-PD-003', name:'浦东国际机场配套建筑', client:'上海机场建设指挥部', area:'T3航站楼 / 屋面', cycle:'专项巡检', status:'已完成', manager:'周然', progress:100, date:'2026-08-08', regions:2, standard:'建筑屋面裂缝与锈蚀检查', plan:'机场屋面专项检查计划'},
  {id:'PRJ-LG-004', name:'临港产业园分布式电站', client:'临港产业区运营中心', area:'一期 / 逆变器区', cycle:'月度巡检', status:'规划中', manager:'陈凯', progress:0, date:'2026-08-22', regions:5, standard:'逆变器与组件异常检查', plan:'2026年8月月度巡检计划'},
])
const tasks = ref([
  {id:'TASK-20260812-001', projectId:'PRJ-HDN-001', project:'华东新能源科技园一期', area:'A区 / 组件区03', regionCode:'A-03', date:'2026-08-12 09:00', pilot:'张伟', drone:'DJI Mavic 3E', status:'待AI分析', files:28, expectedFiles:28, plan:'2026年8月月度巡检计划', note:'完成组件区03 RGB及热成像采集，关注遮挡、裂缝、积水和锈蚀。'},
  {id:'TASK-20260812-002', projectId:'PRJ-HDN-001', project:'华东新能源科技园一期', area:'A区 / 组件区05-08', regionCode:'A-05~08', date:'2026-08-12 13:30', pilot:'李浩', drone:'DJI Mavic 3T', status:'待执行', files:0, expectedFiles:30, plan:'2026年8月月度巡检计划', note:'按任务包完成组件区05-08巡检。'},
  {id:'TASK-20260808-006', projectId:'PRJ-PD-003', project:'浦东国际机场配套建筑', area:'T3 / 西侧屋面', regionCode:'T3-W', date:'2026-08-08 10:00', pilot:'赵磊', drone:'DJI Matrice 30T', status:'已完成', files:19, expectedFiles:19, plan:'机场屋面专项检查计划', note:'专项检查已完成并归档。'},
  {id:'TASK-20260805-003', projectId:'PRJ-SZ-002', project:'苏州工业园区屋顶光伏', area:'5号厂房 / 屋顶', regionCode:'SZ-05', date:'2026-08-05 08:30', pilot:'张伟', drone:'DJI Mavic 3E', status:'已完成', files:16, expectedFiles:16, plan:'2026年第三季度巡检计划', note:'资料已归档。'},
])
const issues = ref([
  {id:'ISS-001', taskId:'TASK-20260812-001', loc:'A-03 / 组件排3 / P-028', type:'光伏板遮挡', time:'2026-08-12 10:24', confidence:'92%', status:'待审核', color:'orange', opinion:''},
  {id:'ISS-002', taskId:'TASK-20260812-001', loc:'A-03 / 组件排3 / P-041', type:'裂缝', time:'2026-08-12 10:31', confidence:'88%', status:'待审核', color:'red', opinion:''},
  {id:'ISS-003', taskId:'TASK-20260812-001', loc:'A-03 / 组件排2 / P-017', type:'积水', time:'2026-08-12 10:46', confidence:'81%', status:'已确认', color:'blue', opinion:'影像证据清晰，纳入本次报告。'},
  {id:'ISS-004', taskId:'TASK-20260812-001', loc:'A-03 / 组件排1 / P-006', type:'锈蚀', time:'2026-08-12 11:02', confidence:'76%', status:'误报', color:'gray', opinion:'复核后判断为光照反射。'},
])
const filteredIssues = computed(() => issueFilter.value === '全部' ? issues.value : issues.value.filter(x=>x.status===issueFilter.value))
const selectedTask = computed(()=>tasks.value.find(x=>x.id===selectedTaskId.value) || tasks.value[0])
const selectedProject = computed(()=>projects.value.find(x=>x.id===selectedProjectId.value) || projects.value[0])
const pendingIssues = computed(()=>issues.value.filter(x=>x.status==='待审核'))
const confirmedIssues = computed(()=>issues.value.filter(x=>['已确认','已纳入报告','人工新增'].includes(x.status)))
const reportIssueCount = computed(()=>confirmedIssues.value.length)
const showToast = (msg) => { toast.value=msg; setTimeout(()=>toast.value='',2400) }
const can = (key) => visibleNav.value.some(item=>item.key===key)
const go = (key) => { if(can(key)){ active.value=key; showProjectDetail.value=false; showTaskDetail.value=false } else showToast(`当前角色无权访问“${nav.find(x=>x.key===key)?.label || key}”`) }
const switchRole = (key) => { roleKey.value=key; showRoleMenu.value=false; active.value='dashboard'; showToast(`已切换为${roles[key].label}，页面按角色权限展示`) }
const addLog = (role,text) => logs.value.unshift({time:'2026-08-13 14:20',role,text})
const statusClass = (status) => ({'执行中':'doing','已确认':'done','已完成':'done','已审核':'done','已交付':'done','已归档':'done','误报':'muted-status','规划中':'pending','待执行':'pending','待调度':'pending','待审核':'pending','待负责人审核':'pending','需复查':'review-status','资料待校验':'review-status','待AI分析':'review-status','异常/需补采':'danger-status'}[status] || 'pending')
const openProject = (project) => { selectedProjectId.value=project.id; showProjectDetail.value=true }
const openTask = (task) => { selectedTaskId.value=task.id; showTaskDetail.value=true }
const startTask = (task) => { task.status='执行中'; addLog('无人机飞手',`开始执行任务 ${task.id}`); showToast('任务已开始，现场执行状态已更新') }
const uploadFiles = () => { const task=selectedTask.value; task.files=task.expectedFiles; task.status='待AI分析'; uploadDone.value=true; addLog('无人机飞手',`上传${task.files}份现场资料，资料完整性校验通过`); showToast('资料已上传并完成任务归档校验') }
const runAnalysis = () => { selectedTask.value.status='待问题审核'; addLog('系统','AI模拟分析完成，生成4个候选问题'); showToast('模拟AI分析完成，候选结果已提交人工审核') }
const updateIssue = (item,status) => { item.status=status; item.opinion=status==='已确认'?'复核确认，纳入报告初稿。':status==='误报'?'人工复核后排除。':'需要补充资料或复查。'; addLog('检查人员',`将${item.id}审核为“${status}”`); showToast(status==='已确认'?'问题已确认，已纳入报告统计':`问题已标记为${status}`) }
const addIssue = () => { issues.value.unshift({id:`ISS-00${issues.value.length+1}`,taskId:selectedTaskId.value,loc:'A-03 / 组件排4 / P-052',type:'人工新增问题',time:'2026-08-13 14:20',confidence:'—',status:'人工新增',color:'purple',opinion:'检查人员现场补充，纳入报告初稿。'}); showAddIssue.value=false; addLog('检查人员','人工新增问题并纳入报告初稿'); showToast('人工问题已创建并纳入报告统计') }
const reviewReport = (status) => { reportStatus.value=status; addLog('项目负责人',`报告${status==='已审核'?'审核通过':'已退回修改'}`); showToast(status==='已审核'?'报告审核通过，可模拟交付':'报告已退回，等待修改') }
const deliverReport = () => { if(reportStatus.value!=='已审核') return showToast('请先完成负责人审核'); reportStatus.value='已交付'; addLog('项目负责人','报告已模拟交付客户并记录版本'); showToast('报告已模拟交付，版本和交付记录已留痕') }

const kpis = computed(()=>[
  ['巡检项目',projects.value.length,'本工作空间演示数据','blue',FolderKanban],
  ['待我处理',roleKey.value==='inspector'?pendingIssues.value.length:tasks.value.filter(t=>['待调度','待执行','待负责人审核'].includes(t.status)).length,roleKey.value==='inspector'?'AI候选待审核':'任务与报告待办','purple',ClipboardList],
  ['已确认问题',confirmedIssues.value.length,'进入报告统计','orange',ScanSearch],
  ['报告状态',reportStatus.value==='已交付'?'已交付':'1',reportStatus.value==='已交付'?'已记录交付版本':reportStatus.value,'green',FileText],
])
const bars=[46,62,52,78,69,88,72,94,80,96,84,100]
</script>

<template>
  <div v-if="!loggedIn" class="login-page">
    <div class="login-art"><div class="art-glow"></div><div class="login-copy"><div class="brand-mark"><Plane :size="22"/></div><div><b>SKYWISE</b><span>INTELLIGENT INSPECTION</span></div></div><div class="login-hero"><p class="eyebrow">ENTERPRISE INSPECTION CLOUD</p><h1>让每一次巡检<br/><em>都有迹可循</em></h1><p>从任务调度到智能识别，构建无人机巡检服务的数字化闭环。</p></div><div class="login-art-footer">© 2026 SKYWISE DIGITAL · 企业级无人机智能巡检平台</div></div>
    <div class="login-form"><div class="login-form-inner"><div class="mobile-brand"><div class="brand-mark"><Plane :size="18"/></div><b>SKYWISE</b></div><p class="eyebrow">欢迎回来</p><h2>登录管理平台</h2><p class="muted">使用您的企业账号继续工作</p><label>企业账号</label><div class="input"><UserRound :size="17"/><input value="admin@skywise.cn" /></div><label>登录密码</label><div class="input"><ShieldCheck :size="17"/><input type="password" value="12345678" /></div><div class="login-options"><span><input type="checkbox" checked/> 记住我</span><a>忘记密码？</a></div><button class="primary login-btn" @click="loggedIn=true">进入平台 <ArrowUpRight :size="17"/></button><p class="demo-tip"><Sparkles :size="15"/> Demo演示账号已预填，可直接登录</p></div></div>
  </div>
  <div v-else class="app-shell">
    <aside class="sidebar"><div class="side-brand"><div class="brand-mark"><Plane :size="19"/></div><div><b>SKYWISE</b><span>INSPECTION CLOUD</span></div></div><div class="workspace"><div class="workspace-avatar">华</div><div><b>华东巡检服务中心</b><span>企业工作空间 · 演示数据</span></div><ChevronDown :size="15"/></div><nav><div class="nav-title">工作台</div><button v-for="item in visibleNav" :key="item.key" :class="['nav-item',{active:active===item.key}]" @click="go(item.key)"><component :is="item.icon" :size="18"/><span>{{item.label}}</span><small v-if="item.badge">{{item.badge}}</small></button><div class="nav-title secondary">系统管理</div><button v-if="roleKey==='admin'" class="nav-item" @click="showToast('基础权限与审计配置为演示占位')"><Settings2 :size="18"/><span>基础设置</span></button></nav><div class="side-bottom"><div class="storage-head"><span>对象存储（模拟）</span><b>68%</b></div><div class="progress"><i style="width:68%"></i></div><span class="storage-text">340 GB / 500 GB · 演示指标</span></div></aside>
    <main class="main"><header class="topbar"><div class="crumb"><Menu :size="20" class="menu-icon"/><span>平台工作台</span><b>/</b><strong>{{nav.find(x=>x.key===active)?.label}}</strong></div><div class="top-actions"><div class="search"><Search :size="17"/><input v-model="query" placeholder="搜索项目、任务或问题..."/></div><button class="icon-btn" @click="showToast('当前无新的站内待办')"><Bell :size="19"/><i v-if="pendingIssues.length"></i></button><div class="user-menu role-menu-anchor" @click="showRoleMenu=!showRoleMenu"><div class="user-avatar">{{currentRole.short}}</div><div><b>{{currentRole.label}}</b><span>{{currentRole.desc}}</span></div><ChevronDown :size="15"/><div v-if="showRoleMenu" class="role-menu"><div class="role-menu-title">Demo角色切换</div><button v-for="(role,key) in roles" :key="key" :class="{selected:key===roleKey}" @click.stop="switchRole(key)"><span class="role-dot">{{role.short}}</span><span><b>{{role.label}}</b><small>{{role.desc}}</small></span><Check v-if="key===roleKey" :size="15"/></button></div></div></div></header><div class="demo-strip"><span>角色：{{currentRole.label}}</span></div>
      <div class="content">
        <section v-if="active==='dashboard'" class="page"><div class="page-title"><div><p class="eyebrow">TUESDAY, AUGUST 12, 2026</p><h1>早上好，管理员 <span>👋</span></h1><p class="muted">今天有 <b class="text-blue">8 个任务</b> 待处理，巡检中心运行正常。</p></div><button class="primary" @click="showNewProject=true"><Plus :size="17"/> 新建巡检项目</button></div><div class="kpi-grid"><div v-for="item in kpis" class="kpi card"><div class="kpi-top"><span>{{item[0]}}</span><div :class="['kpi-icon',item[3]]"><component :is="item[0]==='AI发现问题'?ScanSearch:item[0]==='已生成报告'?FileText:item[0]==='待执行任务'?ClipboardList:FolderKanban" :size="19"/></div></div><strong>{{item[1]}}</strong><span :class="['kpi-foot',item[3]]">{{item[2]}} <ArrowUpRight :size="13"/></span></div></div><div class="dashboard-grid"><div class="card chart-card"><div class="card-title"><div><h3>巡检任务趋势</h3><span>近12个月任务完成情况</span></div><button class="select">近一年 <ChevronDown :size="14"/></button></div><div class="chart"><div class="y-labels"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div class="chart-main"><div class="grid-lines"><i></i><i></i><i></i><i></i><i></i></div><div class="bars"><div v-for="(bar,i) in bars" class="bar-wrap"><div class="bar" :style="{height:bar+'%'}"><b v-if="i===11">{{bar}}</b></div><span>{{['9月','10月','11月','12月','1月','2月','3月','4月','5月','6月','7月','8月'][i]}}</span></div></div></div></div></div><div class="card today-card"><div class="card-title"><div><h3>今日任务</h3><span>2026年8月12日</span></div><button class="text-btn" @click="go('tasks')">查看全部 →</button></div><div class="task-mini" v-for="t in tasks.slice(0,3)"><div class="task-time"><b>{{t.date.split(' ')[1]}}</b><span>{{t.status==='执行中'?'进行中':'待执行'}}</span></div><div class="task-info"><b>{{t.area}}</b><span>{{t.pilot}} · {{t.drone}}</span></div><span :class="['status',t.status==='执行中'?'doing':'pending']">{{t.status}}</span></div></div></div><div class="card recent-card"><div class="card-title"><div><h3>最近巡检项目</h3><span>项目进展实时更新</span></div><button class="text-btn" @click="go('projects')">全部项目 →</button></div><div class="project-row" v-for="project in projects.slice(0,3)"><div class="project-symbol"><Plane :size="17"/></div><div class="project-name"><b>{{project.name}}</b><span>{{project.client}}</span></div><div class="project-area"><MapPin :size="14"/> {{project.area}}</div><div class="project-progress"><div><span>完成度</span><b>{{project.progress}}%</b></div><div class="progress"><i :style="{width:project.progress+'%'}"></i></div></div><span :class="['status',project.status==='巡检中'?'doing':project.status==='已完成'?'done':'pending']">{{project.status}}</span></div></div></section>

        <section v-else-if="active==='projects'" class="page"><div class="page-title"><div><p class="eyebrow">OPERATIONS / PROJECTS</p><h1>巡检项目</h1><p class="muted">统一管理客户项目、区域范围与巡检周期。</p></div><button class="primary" @click="showNewProject=true"><Plus :size="17"/> 新建项目</button></div><div class="filterbar card"><div class="search inline"><Search :size="16"/><input placeholder="搜索项目名称或客户"/></div><button class="filter-btn">全部状态 <ChevronDown :size="14"/></button><button class="filter-btn">巡检周期 <ChevronDown :size="14"/></button><span class="filter-count">共 {{projects.length}} 个项目</span></div><div class="card table-card"><table><thead><tr><th>项目名称</th><th>客户名称</th><th>巡检区域</th><th>巡检周期</th><th>项目负责人</th><th>项目状态</th><th>完成度</th><th></th></tr></thead><tbody><tr v-for="project in projects"><td><div class="table-main"><div class="project-symbol small"><Plane :size="15"/></div><b>{{project.name}}</b></div><small>{{project.date}} 更新</small></td><td>{{project.client}}</td><td><MapPin :size="14"/> {{project.area}}</td><td>{{project.cycle}}</td><td>{{project.manager}}</td><td><span :class="['status',project.status==='巡检中'?'doing':project.status==='已完成'?'done':'pending']">{{project.status}}</span></td><td><div class="mini-progress"><i :style="{width:project.progress+'%'}"></i></div><small>{{project.progress}}%</small></td><td><button class="link-btn" @click="detailProject=true">查看详情</button></td></tr></tbody></table></div></section>

        <section v-else-if="active==='tasks'" class="page"><div class="page-title"><div><p class="eyebrow">OPERATIONS / TASKS</p><h1>巡检任务</h1><p class="muted">从任务生成、资源调度到现场执行，全程留痕。</p></div><button class="primary" @click="showToast('任务创建向导已打开')"><Plus :size="17"/> 新建任务</button></div><div class="task-banner"><div class="banner-icon"><ClipboardList :size="23"/></div><div><b>今日任务执行情况</b><span>已完成 1 个 · 执行中 1 个 · 待执行 1 个</span></div><div class="banner-progress"><div class="progress"><i style="width:33%"></i></div><b>33%</b></div><button class="ghost-light" @click="go('ai')">演示上传资料 →</button></div><div class="filterbar card"><div class="search inline"><Search :size="16"/><input placeholder="搜索任务编号、项目或飞手"/></div><button class="filter-btn">全部状态 <ChevronDown :size="14"/></button><button class="filter-btn"><CalendarDays :size="14"/> 执行日期 <ChevronDown :size="14"/></button></div><div class="card table-card"><table><thead><tr><th>任务编号</th><th>项目 / 区域</th><th>执行日期</th><th>飞手</th><th>无人机型号</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="t in tasks"><td><b class="mono">{{t.id}}</b></td><td><div class="table-main"><b>{{t.project}}</b></div><small>{{t.area}}</small></td><td><Clock3 :size="14"/> {{t.date}}</td><td>{{t.pilot}}</td><td>{{t.drone}}</td><td><span :class="['status',t.status==='执行中'?'doing':t.status==='已完成'?'done':'pending']">{{t.status}}</span></td><td><button class="link-btn" @click="t.status==='待执行' ? (t.status='执行中',showToast('任务已开始执行')) : go('ai')">{{t.status==='待执行'?'开始任务':'查看任务'}}</button></td></tr></tbody></table></div></section>

        <section v-else-if="active==='ai'" class="page"><div class="page-title"><div><p class="eyebrow">INTELLIGENCE / VISION ANALYSIS</p><h1>AI影像分析 <span class="live-dot">● 实时分析</span></h1><p class="muted">上传巡检影像，AI将自动筛查候选异常并交由人工复核。</p></div><button class="secondary" @click="uploadDone=!uploadDone"><Upload :size="17"/> {{uploadDone?'重新上传影像':'上传巡检影像'}}</button></div><div class="ai-notice"><Sparkles :size="19"/><div><b>AI辅助识别</b><span>识别结果仅作为辅助判断，最终结论需由专业人员人工确认。</span></div><span class="notice-tag">模型 v2.4.1</span></div><div class="ai-layout"><div class="card image-card"><div class="card-title"><div><h3>影像预览</h3><span>任务：TASK-20260812-001 · 组件区03</span></div><span class="image-count">1 / 24</span></div><div class="inspection-image"><div class="image-sky"></div><div class="solar-field"><i v-for="i in 18" :key="i"></i></div><div class="detect-box box-one"><span>遮挡 · 92%</span></div><div class="detect-box box-two"><span>裂缝 · 88%</span></div><div class="image-overlay"><span>IMG_20260812_102431.JPG</span><span>热成像 / RGB</span></div></div><div class="image-tools"><button>‹</button><div class="thumb active"><div class="thumb-grid"></div></div><div class="thumb"><div class="thumb-grid warm"></div></div><div class="thumb"><div class="thumb-grid dark"></div></div><button>›</button></div></div><div class="card detection-card"><div class="card-title"><div><h3>AI识别结果</h3><span>已分析 24 张影像 · 发现 4 个候选问题</span></div><span class="analysis-done"><Check :size="14"/> 分析完成</span></div><div class="detection-list"><div v-for="issue in issues" class="detection-item" @click="go('issues')"><div :class="['detect-dot',issue.color]"><ScanSearch :size="16"/></div><div class="detect-content"><b>{{issue.type}}</b><span>{{issue.loc}}</span></div><strong>{{issue.confidence}}</strong><ChevronDown :size="15"/></div></div><button class="primary full" @click="go('issues')">进入问题审核 <ArrowUpRight :size="16"/></button></div></div></section>

        <section v-else-if="active==='issues'" class="page"><div class="page-title"><div><p class="eyebrow">QUALITY / ISSUE REVIEW</p><h1>问题审核</h1><p class="muted">审核AI识别结果，沉淀可追溯的问题证据。</p></div><button class="secondary" @click="showAddIssue=true"><Plus :size="17"/> 人工新增问题</button></div><div class="issue-summary"><div><span>待审核</span><b>{{issues.filter(x=>x.status==='待审核').length}}</b><small>需要您确认</small></div><div><span>已确认有效</span><b class="blue-number">{{issues.filter(x=>x.status==='已确认').length}}</b><small>将纳入巡检报告</small></div><div><span>误报</span><b>{{issues.filter(x=>x.status==='误报').length}}</b><small>已排除</small></div><div><span>本次AI发现</span><b>4</b><small>来自 24 张影像</small></div></div><div class="filter-tabs"><button v-for="f in ['全部','待审核','已确认','误报']" :class="{selected:issueFilter===f}" @click="issueFilter=f">{{f}} <em v-if="f!=='全部'">{{issues.filter(x=>x.status===f).length}}</em></button></div><div class="card table-card"><table><thead><tr><th>问题位置</th><th>问题类型</th><th>发现时间</th><th>AI结果</th><th>审核状态</th><th>审核操作</th></tr></thead><tbody><tr v-for="issue in filteredIssues"><td><div class="table-main"><div :class="['detect-dot small-dot',issue.color]"><ScanSearch :size="14"/></div><b>{{issue.loc}}</b></div></td><td><span class="type-chip">{{issue.type}}</span></td><td>{{issue.time}}</td><td><b class="confidence">{{issue.confidence}}</b><small> · 模型v2.4.1</small></td><td><span :class="['status',issue.status==='已确认'?'done':issue.status==='误报'?'muted-status':'pending']">{{issue.status}}</span></td><td><div v-if="issue.status==='待审核'" class="issue-actions"><button class="icon-action good" title="确认有效" @click="updateIssue(issue,'已确认')"><Check :size="15"/></button><button class="icon-action bad" title="误报" @click="updateIssue(issue,'误报')"><X :size="15"/></button><button class="icon-action review" title="需要复查" @click="updateIssue(issue,'需复查')"><RotateCcw :size="15"/></button></div><span v-else class="muted">已处理</span></td></tr></tbody></table></div></section>

        <section v-else-if="active==='history'" class="page"><div class="page-title"><div><p class="eyebrow">INSIGHTS / COMPARISON</p><h1>历史对比</h1><p class="muted">同一区域跨时间对比，直观看见问题变化趋势。</p></div><button class="filter-btn">A区 / 组件区03 <ChevronDown :size="14"/></button></div><div class="history-head card"><div><span class="eyebrow">对比对象</span><h3>华东新能源科技园一期 · A区 / 组件区03</h3><p class="muted">组件数量 1,280 块 · 最近巡检 2026-08-12</p></div><div class="trend-stat"><span>问题数量</span><b>4 <i>+2</i></b><small>较上次巡检上升 100%</small></div></div><div class="compare-grid"><div class="card compare-card"><div class="compare-title"><div><b>上次巡检</b><span>2026-07-12</span></div><span class="old-tag">历史影像</span></div><div class="compare-image old"><div class="solar-field small-grid"><i v-for="i in 24" :key="i"></i></div><div class="old-mark mark-a"></div></div><div class="compare-foot"><span>发现问题 <b>2</b></span><span>已确认 <b>2</b></span></div></div><div class="compare-arrow">→</div><div class="card compare-card current"><div class="compare-title"><div><b>本次巡检</b><span>2026-08-12</span></div><span class="new-tag">最新影像</span></div><div class="compare-image"><div class="solar-field small-grid"><i v-for="i in 24" :key="i"></i></div><div class="old-mark mark-a"></div><div class="new-mark mark-b"></div><div class="new-mark mark-c"></div></div><div class="compare-foot"><span>发现问题 <b class="red-text">4</b></span><span>新增 <b class="red-text">2</b></span></div></div></div><div class="card timeline-card"><div class="card-title"><div><h3>问题变化趋势</h3><span>按巡检批次统计问题数量</span></div></div><div class="trend-chart"><div class="trend-line"><svg viewBox="0 0 700 190" preserveAspectRatio="none"><path d="M0,145 C80,145 100,130 170,135 S250,120 320,125 S405,105 470,110 S555,50 700,28" fill="none" stroke="#ef6d5f" stroke-width="4"/><path d="M0,145 C80,145 100,130 170,135 S250,120 320,125 S405,105 470,110 S555,50 700,28 L700,190 L0,190Z" fill="url(#fill)" opacity=".16"/><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#ef6d5f"/><stop offset="1" stop-color="#fff"/></linearGradient></defs><circle cx="700" cy="28" r="6" fill="#ef6d5f"/></svg></div><div class="trend-labels"><span>2026-03</span><span>2026-04</span><span>2026-05</span><span>2026-06</span><span>2026-07</span><span>2026-08</span></div></div></div></section>

        <section v-else-if="active==='reports'" class="page"><div class="page-title"><div><p class="eyebrow">DELIVERY / REPORTS</p><h1>报告管理</h1><p class="muted">自动汇总巡检数据，审核后生成专业交付报告。</p></div><button class="primary" @click="showToast('报告生成任务已提交')"><FileText :size="17"/> 生成巡检报告</button></div><div class="report-feature card"><div class="report-cover"><div class="cover-top"><div class="brand-mark"><Plane :size="17"/></div><span>巡检报告 · 2026 / 08</span></div><div class="cover-title"><span>INSPECTION REPORT</span><h2>华东新能源科技园<br/>一期月度巡检报告</h2><p>专业 · 高效 · 可追溯</p></div><div class="cover-bottom"><span>SKYWISE DIGITAL</span><span>REPORT-20260812-001</span></div></div><div class="report-info"><div class="report-label">报告预览</div><h2>华东新能源科技园一期<br/>月度无人机巡检报告</h2><p class="muted">报告编号：REPORT-20260812-001</p><div class="report-meta"><span><b>项目客户</b>华东新能源科技有限公司</span><span><b>巡检区域</b>A区 / 组件区01-08</span><span><b>巡检日期</b>2026年8月12日</span><span><b>报告状态</b><em>待负责人审核</em></span></div><div class="report-buttons"><button class="primary" @click="showToast('报告预览已打开')">查看报告 <ArrowUpRight :size="16"/></button><button class="secondary" @click="showToast('PDF导出已开始')">导出PDF <FileText :size="16"/></button></div></div></div><div class="report-stats"><div class="card"><span>巡检面积</span><b>48,600 <small>㎡</small></b><i>覆盖率 98.2%</i></div><div class="card"><span>采集影像</span><b>248 <small>张</small></b><i>含热成像 86 张</i></div><div class="card"><span>发现问题</span><b>4 <small>项</small></b><i class="red-text">待确认 2 项</i></div><div class="card"><span>报告页数</span><b>26 <small>页</small></b><i>已自动生成初稿</i></div></div></section>

        <section v-else-if="active==='fleet'" class="page"><div class="page-title"><div><p class="eyebrow">OPERATIONS / FLEET</p><h1>飞手和设备管理</h1><p class="muted">统一维护飞手资质、负责区域与无人机设备状态。</p></div><button class="primary" @click="showToast('新增资源向导已打开')"><Plus :size="17"/> 新增资源</button></div><div class="issue-summary"><div><span>可用飞手</span><b>18</b><small>资质均在有效期内</small></div><div><span>无人机设备</span><b class="blue-number">26</b><small>含热成像设备 8 台</small></div><div><span>执行中设备</span><b>07</b><small>当前任务占用</small></div><div><span>待维保提醒</span><b class="red-text">02</b><small>建议本周处理</small></div></div><div class="fleet-grid"><div class="card table-card"><div class="card-title fleet-card-title"><div><h3>飞手信息</h3><span>资质与负责区域</span></div><button class="text-btn">查看全部 →</button></div><table><thead><tr><th>姓名</th><th>资质等级</th><th>负责区域</th><th>当前状态</th></tr></thead><tbody><tr v-for="f in [{n:'张伟',level:'高级飞手',area:'华东区域',s:'执行中'},{n:'李浩',level:'中级飞手',area:'苏州园区',s:'空闲'},{n:'赵磊',level:'高级飞手',area:'浦东机场',s:'空闲'},{n:'陈凯',level:'初级飞手',area:'临港产业园',s:'培训中'}]"><td><div class="table-main"><div class="user-avatar mini-avatar">{{f.n.slice(0,1)}}</div><b>{{f.n}}</b></div></td><td><span class="level-chip">{{f.level}}</span></td><td>{{f.area}}</td><td><span :class="['status',f.s==='执行中'?'doing':f.s==='空闲'?'done':'pending']">{{f.s}}</span></td></tr></tbody></table></div><div class="card table-card"><div class="card-title fleet-card-title"><div><h3>无人机设备</h3><span>设备编号与使用状态</span></div><button class="text-btn">设备台账 →</button></div><table><thead><tr><th>型号</th><th>设备编号</th><th>使用状态</th></tr></thead><tbody><tr v-for="d in [{m:'DJI Mavic 3E',id:'DJI-M3E-0068',s:'执行中'},{m:'DJI Mavic 3T',id:'DJI-M3T-0021',s:'空闲'},{m:'DJI Matrice 30T',id:'DJI-M30T-0008',s:'空闲'},{m:'DJI Mavic 3E',id:'DJI-M3E-0042',s:'待维保'}]"><td><div class="table-main"><div class="drone-symbol"><Plane :size="14"/></div><b>{{d.m}}</b></div></td><td class="mono">{{d.id}}</td><td><span :class="['status',d.s==='执行中'?'doing':d.s==='空闲'?'done':'pending']">{{d.s}}</span></td></tr></tbody></table></div></div></section>
      </div>
    </main>
    <div v-if="toast" class="toast"><Check :size="16"/> {{toast}}</div>
    <div v-if="showNewProject" class="modal-mask" @click.self="showNewProject=false"><div class="modal"><div class="modal-head"><div><span class="eyebrow">NEW PROJECT</span><h2>新建巡检项目</h2></div><button class="close" @click="showNewProject=false"><X/></button></div><label>项目名称</label><div class="input"><FolderKanban :size="17"/><input placeholder="请输入项目名称" value="华东新能源科技园二期"/></div><label>客户名称</label><div class="input"><UserRound :size="17"/><input placeholder="请输入客户名称"/></div><div class="two-input"><div><label>巡检周期</label><button class="select full-select">月度巡检 <ChevronDown :size="14"/></button></div><div><label>项目负责人</label><button class="select full-select">请选择负责人 <ChevronDown :size="14"/></button></div></div><div class="modal-actions"><button class="secondary" @click="showNewProject=false">取消</button><button class="primary" @click="showNewProject=false;showToast('巡检项目创建成功')">创建项目 <ArrowUpRight :size="15"/></button></div></div></div>
    <div v-if="showAddIssue" class="modal-mask" @click.self="showAddIssue=false"><div class="modal"><div class="modal-head"><div><span class="eyebrow">MANUAL ISSUE</span><h2>人工新增问题</h2></div><button class="close" @click="showAddIssue=false"><X/></button></div><label>问题位置</label><div class="input"><MapPin :size="17"/><input value="A区 / 组件区04 / P-052"/></div><label>问题类型</label><button class="select full-select">请选择问题类型 <ChevronDown :size="14"/></button><label>问题描述</label><textarea placeholder="请描述现场发现的问题..."></textarea><div class="modal-actions"><button class="secondary" @click="showAddIssue=false">取消</button><button class="primary" @click="addIssue">创建问题 <ArrowUpRight :size="15"/></button></div></div></div>
  </div>
</template>
