<script setup>
import { computed, ref } from 'vue'
import { LayoutDashboard, FolderKanban, ClipboardList, Plane, ScanSearch, ShieldCheck, GitCompare, FileText, Bell, Search, ChevronDown, Plus, Upload, Check, X, RotateCcw, MapPin, CalendarDays, Clock3, ArrowUpRight, Menu, UserRound, Settings2, Sparkles, History, PackageCheck, Send, Eye } from 'lucide-vue-next'

const loggedIn=ref(false), active=ref('dashboard'), roleKey=ref('manager'), toast=ref(''), query=ref(''), issueFilter=ref('全部')
const roleMenu=ref(false), projectDetail=ref(false), taskDetail=ref(false), newProject=ref(false), addIssueModal=ref(false), selectedTaskId=ref('TASK-20260812-001'), selectedProjectId=ref('PRJ-HDN-001'), reportStatus=ref('待负责人审核')
const roles={manager:{label:'项目负责人',short:'负',desc:'项目交付与报告审核'},dispatcher:{label:'调度人员',short:'调',desc:'任务排班与资源调度'},pilot:{label:'无人机飞手',short:'飞',desc:'现场执行与资料上传'},inspector:{label:'检查人员',short:'检',desc:'影像复核与问题审核'},admin:{label:'系统管理员',short:'管',desc:'账号、权限与审计'}}
const currentRole=computed(()=>roles[roleKey.value])
const nav=[
 {key:'dashboard',label:'巡检工作台',icon:LayoutDashboard,roles:Object.keys(roles)},
 {key:'projects',label:'项目与区域',icon:FolderKanban,roles:['manager','dispatcher','inspector','admin']},
 {key:'tasks',label:'任务调度',icon:ClipboardList,roles:Object.keys(roles)},
 {key:'fleet',label:'飞手与设备',icon:Plane,roles:['manager','dispatcher','admin']},
 {key:'ai',label:'AI影像分析',icon:ScanSearch,badge:'辅助',roles:['manager','pilot','inspector','admin']},
 {key:'issues',label:'问题审核',icon:ShieldCheck,roles:['manager','inspector','admin']},
 {key:'history',label:'历史对比',icon:GitCompare,roles:['manager','inspector','admin']},
 {key:'reports',label:'报告交付',icon:FileText,roles:['manager','inspector','admin']},
]
const visibleNav=computed(()=>nav.filter(n=>n.roles.includes(roleKey.value)))
const projects=ref([
 {id:'PRJ-HDN-001',name:'华东新能源科技园一期',client:'华东新能源科技有限公司',area:'A区 / 组件区01-08',cycle:'月度巡检',status:'执行中',manager:'李晨',progress:72,date:'2026-08-12',regions:8,standard:'光伏组件外观与热成像检查',plan:'2026年8月月度巡检计划'},
 {id:'PRJ-SZ-002',name:'苏州工业园区屋顶光伏',client:'苏州工业园区发展集团',area:'5号厂房 / 屋顶',cycle:'季度巡检',status:'待执行',manager:'王欣',progress:18,date:'2026-08-18',regions:3,standard:'屋面组件与排水检查',plan:'2026年第三季度巡检计划'},
 {id:'PRJ-PD-003',name:'浦东国际机场配套建筑',client:'上海机场建设指挥部',area:'T3航站楼 / 屋面',cycle:'专项巡检',status:'已完成',manager:'周然',progress:100,date:'2026-08-08',regions:2,standard:'建筑屋面裂缝与锈蚀检查',plan:'机场屋面专项检查计划'},
])
const tasks=ref([
 {id:'TASK-20260812-001',projectId:'PRJ-HDN-001',project:'华东新能源科技园一期',area:'A区 / 组件区03',region:'A-03',date:'2026-08-12 09:00',pilot:'张伟',drone:'DJI Mavic 3E',status:'待AI分析',files:28,total:28,note:'完成组件区03 RGB及热成像采集，关注遮挡、裂缝、积水和锈蚀。'},
 {id:'TASK-20260812-002',projectId:'PRJ-HDN-001',project:'华东新能源科技园一期',area:'A区 / 组件区05-08',region:'A-05~08',date:'2026-08-12 13:30',pilot:'李浩',drone:'DJI Mavic 3T',status:'待执行',files:0,total:30,note:'按任务包完成组件区05-08巡检。'},
 {id:'TASK-20260808-006',projectId:'PRJ-PD-003',project:'浦东国际机场配套建筑',area:'T3 / 西侧屋面',region:'T3-W',date:'2026-08-08 10:00',pilot:'赵磊',drone:'DJI Matrice 30T',status:'已完成',files:19,total:19,note:'专项检查已完成并归档。'},
])
const issues=ref([
 {id:'ISS-001',taskId:'TASK-20260812-001',loc:'A-03 / 组件排3 / P-028',type:'光伏板遮挡',time:'2026-08-12 10:24',confidence:'92%',status:'待审核',color:'orange',opinion:''},
 {id:'ISS-002',taskId:'TASK-20260812-001',loc:'A-03 / 组件排3 / P-041',type:'裂缝',time:'2026-08-12 10:31',confidence:'88%',status:'待审核',color:'red',opinion:''},
 {id:'ISS-003',taskId:'TASK-20260812-001',loc:'A-03 / 组件排2 / P-017',type:'积水',time:'2026-08-12 10:46',confidence:'81%',status:'已确认',color:'blue',opinion:'影像证据清晰，纳入本次报告。'},
 {id:'ISS-004',taskId:'TASK-20260812-001',loc:'A-03 / 组件排1 / P-006',type:'锈蚀',time:'2026-08-12 11:02',confidence:'76%',status:'误报',color:'gray',opinion:'复核后判断为光照反射。'},
])
const logs=ref([{time:'2026-08-12 11:20',role:'检查人员',text:'完成影像归档校验，任务进入待AI分析'},{time:'2026-08-12 10:05',role:'无人机飞手',text:'上传28份现场资料（照片、视频、飞行记录）'},{time:'2026-08-12 09:00',role:'调度人员',text:'确认张伟 / DJI Mavic 3E执行任务'},{time:'2026-08-11 16:30',role:'项目负责人',text:'由月度巡检计划生成任务'}])
const selectedTask=computed(()=>tasks.value.find(t=>t.id===selectedTaskId.value)||tasks.value[0]), selectedProject=computed(()=>projects.value.find(p=>p.id===selectedProjectId.value)||projects.value[0])
const pending=computed(()=>issues.value.filter(i=>i.status==='待审核')), confirmed=computed(()=>issues.value.filter(i=>['已确认','人工新增'].includes(i.status))), filteredIssues=computed(()=>issueFilter.value==='全部'?issues.value:issues.value.filter(i=>i.status===issueFilter.value))
const statusClass=s=>({'执行中':'doing','已完成':'done','已确认':'done','已审核':'done','已交付':'done','误报':'muted-status','待执行':'pending','待审核':'pending','待负责人审核':'pending','待AI分析':'review-status','待问题审核':'review-status','需复查':'review-status','人工新增':'review-status'}[s]||'pending')
const kpis=computed(()=>[['巡检项目',projects.value.length,'工作空间演示数据','blue',FolderKanban],['待我处理',roleKey.value==='inspector'?pending.value.length:tasks.value.filter(t=>['待执行','待负责人审核'].includes(t.status)).length,roleKey.value==='inspector'?'AI候选待审核':'任务与报告待办','purple',ClipboardList],['已确认问题',confirmed.value.length,'进入报告统计','orange',ScanSearch],['报告状态',reportStatus.value==='已交付'?'已交付':'1',reportStatus.value,'green',FileText]])
const showToast=m=>{toast.value=m;setTimeout(()=>toast.value='',2600)}, addLog=(role,text)=>logs.value.unshift({time:'2026-08-13 14:20',role,text})
const go=k=>{if(visibleNav.value.some(n=>n.key===k)){active.value=k;projectDetail.value=false;taskDetail.value=false}else showToast('当前角色无权访问该模块')}
const switchRole=k=>{roleKey.value=k;roleMenu.value=false;active.value='dashboard';showToast(`已切换为${roles[k].label}`)}
const openProject=p=>{selectedProjectId.value=p.id;projectDetail.value=true}, openTask=t=>{selectedTaskId.value=t.id;taskDetail.value=true}
const startTask=t=>{t.status='执行中';addLog('无人机飞手',`开始执行任务 ${t.id}`);showToast('任务已开始执行')}
const uploadFiles=()=>{selectedTask.value.files=selectedTask.value.total;selectedTask.value.status='资料待校验';addLog('无人机飞手',`上传${selectedTask.value.files}份现场资料，进入资料完整性校验`);setTimeout(()=>{selectedTask.value.status='待AI分析';addLog('系统','资料归属与完整性校验通过，任务进入待AI分析');showToast('资料已归档，质量校验通过，等待AI分析')},350)}
const runAnalysis=()=>{if(selectedTask.value.status==='资料待校验')return showToast('资料正在校验，请稍候');selectedTask.value.status='待问题审核';addLog('系统','AI模拟分析完成，生成4个候选问题');showToast('模拟AI分析完成，候选结果已提交人工审核')}
const updateIssue=(i,s)=>{i.status=s;i.opinion=s==='已确认'?'复核确认，纳入报告初稿。':s==='误报'?'人工复核后排除。':'需要补充资料或复查。';addLog('检查人员',`将${i.id}审核为“${s}”`);if(pending.value.length===0)selectedTask.value.status='待负责人审核';showToast(s==='已确认'?'问题已确认，已纳入报告统计':`问题已标记为${s}`)}
const addIssue=()=>{issues.value.unshift({id:`ISS-00${issues.value.length+1}`,taskId:selectedTaskId.value,loc:'A-03 / 组件排4 / P-052',type:'人工新增问题',time:'2026-08-13 14:20',confidence:'—',status:'人工新增',color:'purple',opinion:'检查人员现场补充，纳入报告初稿。'});addIssueModal.value=false;showToast('人工问题已创建并纳入报告统计')}
const reviewReport=s=>{reportStatus.value=s;addLog('项目负责人',`报告${s==='已审核'?'审核通过':'已退回修改'}`);showToast(s==='已审核'?'报告审核通过':'报告已退回修改')}, deliver=()=>{if(reportStatus.value!=='已审核')return showToast('请先完成负责人审核');reportStatus.value='已交付';addLog('项目负责人','报告已模拟交付客户并记录版本');showToast('报告已模拟交付并留痕')}
</script>

<template>
<div v-if="!loggedIn" class="login-page"><div class="login-art"><div class="art-glow"></div><div class="login-copy"><div class="brand-mark"><Plane :size="22"/></div><div><b>SKYWISE</b><span>INTELLIGENT INSPECTION</span></div></div><div class="login-hero"><p class="eyebrow">ENTERPRISE INSPECTION CLOUD</p><h1>让每一次巡检<br/><em>都有迹可循</em></h1><p>从任务调度到智能识别，构建无人机巡检服务的数字化闭环。</p></div><div class="login-art-footer">© 2026 SKYWISE DIGITAL · 演示数据 / 模拟数据</div></div><div class="login-form"><div class="login-form-inner"><h2>登录巡检管理平台</h2><p class="muted"></p><label>企业账号</label><div class="input"><UserRound :size="17"/><input value="demo@skywise.cn"/></div><label>登录密码</label><div class="input"><ShieldCheck :size="17"/><input type="password" value="12345678"/></div><button class="primary login-btn" @click="loggedIn=true">进入平台 <ArrowUpRight :size="17"/></button><p class="demo-tip"></p></div></div></div>
<div v-else class="app-shell"><aside class="sidebar"><div class="side-brand"><div class="brand-mark"><Plane :size="19"/></div><div><b>SKYWISE</b><span>INSPECTION CLOUD</span></div></div><div class="workspace"><div class="workspace-avatar">华</div><div><b>华东巡检服务中心</b><span>企业工作空间 · 演示数据</span></div></div><nav><div class="nav-title">工作台</div><button v-for="n in visibleNav" :key="n.key" :class="['nav-item',{active:active===n.key}]" @click="go(n.key)"><component :is="n.icon" :size="18"/><span>{{n.label}}</span><small v-if="n.badge">{{n.badge}}</small></button><div class="nav-title secondary">系统管理</div><button v-if="roleKey==='admin'" class="nav-item" @click="showToast('基础权限与审计配置为演示占位')"><Settings2 :size="18"/><span>基础设置</span></button></nav><div class="side-bottom"><div class="storage-head"><span>对象存储（模拟）</span><b>68%</b></div><div class="progress"><i style="width:68%"></i></div><span class="storage-text">340 GB / 500 GB · 演示指标</span></div></aside><main class="main"><header class="topbar"><div class="crumb"><Menu :size="20"/><span>平台工作台</span><b>/</b><strong>{{nav.find(n=>n.key===active)?.label}}</strong></div><div class="top-actions"><div class="search"><Search :size="17"/><input v-model="query" placeholder="搜索项目、任务或问题..."/></div><button class="icon-btn" @click="showToast('当前无新的站内待办')"><Bell :size="19"/><i v-if="pending.length"></i></button><div class="user-menu role-menu-anchor" @click="roleMenu=!roleMenu"><div class="user-avatar">{{currentRole.short}}</div><div><b>{{currentRole.label}}</b><span>{{currentRole.desc}}</span></div><ChevronDown :size="15"/><div v-if="roleMenu" class="role-menu"><div class="role-menu-title">Demo角色切换</div><button v-for="(r,k) in roles" :key="k" @click.stop="switchRole(k)"><span class="role-dot">{{r.short}}</span><span><b>{{r.label}}</b><small>{{r.desc}}</small></span><Check v-if="k===roleKey" :size="15"/></button></div></div></div></header><div class="demo-strip"><span>角色：{{currentRole.label}}</span></div><div class="content">
<section v-if="active==='dashboard'" class="page"><div class="page-title"><div><p class="eyebrow">TUESDAY, AUGUST 13, 2026</p><h1>你好，{{currentRole.label}} 👋</h1><p class="muted">围绕项目、任务、影像、问题和报告，查看当前业务闭环进度。</p></div><button v-if="['manager','admin'].includes(roleKey)" class="primary" @click="newProject=true"><Plus :size="17"/> 新建巡检项目</button></div><div class="kpi-grid"><div v-for="i in kpis" :key="i[0]" class="kpi card"><div class="kpi-top"><span>{{i[0]}}</span><div :class="['kpi-icon',i[3]]"><component :is="i[4]" :size="19"/></div></div><strong>{{i[1]}}</strong><span :class="['kpi-foot',i[3]]">{{i[2]}}</span></div></div><div class="dashboard-grid"><div class="card chart-card"><div class="card-title"><div><h3>巡检任务趋势</h3><span>近12个月任务完成情况（演示数据）</span></div></div><div class="chart"><div class="y-labels"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div class="chart-main"><div class="grid-lines"><i></i><i></i><i></i><i></i><i></i></div><div class="bars"><div v-for="(b,i) in [46,62,52,78,69,88,72,94,80,96,84,100]" :key="i" class="bar-wrap"><div class="bar" :style="{height:b+'%'}"></div><span>{{['9月','10月','11月','12月','1月','2月','3月','4月','5月','6月','7月','8月'][i]}}</span></div></div></div></div></div><div class="card today-card"><div class="card-title"><div><h3>当前任务与待办</h3><span>状态由主案例联动</span></div><button class="text-btn" @click="go('tasks')">查看全部 →</button></div><div v-for="t in tasks" :key="t.id" class="task-mini"><div class="task-time"><b>{{t.date.split(' ')[1]}}</b><span>{{t.status}}</span></div><div class="task-info"><b>{{t.area}}</b><span>{{t.pilot}} · {{t.drone}}</span></div><span :class="['status',statusClass(t.status)]">{{t.status}}</span></div></div></div><div class="card recent-card"><div class="card-title"><div><h3>最近巡检项目</h3><span>项目、区域和任务统一关联</span></div><button class="text-btn" @click="go('projects')">全部项目 →</button></div><div v-for="p in projects" :key="p.id" class="project-row"><div class="project-symbol"><Plane :size="17"/></div><div class="project-name"><b>{{p.name}}</b><span>{{p.client}}</span></div><div class="project-area"><MapPin :size="14"/> {{p.area}}</div><div class="project-progress"><div><span>完成度</span><b>{{p.progress}}%</b></div><div class="progress"><i :style="{width:p.progress+'%'}"></i></div></div><span :class="['status',statusClass(p.status)]">{{p.status}}</span></div></div></section>
<section v-else-if="active==='projects'" class="page"><div class="page-title"><div><p class="eyebrow">OPERATIONS / PROJECTS</p><h1>项目与区域</h1><p class="muted">维护客户项目、区域、巡检计划和检查标准。</p></div></div><div class="card table-card"><table><thead><tr><th>项目名称</th><th>客户</th><th>区域与计划</th><th>周期</th><th>负责人</th><th>状态</th><th>完成度</th><th></th></tr></thead><tbody><tr v-for="p in projects" :key="p.id"><td><b>{{p.name}}</b><small>{{p.id}}</small></td><td>{{p.client}}</td><td>{{p.area}}<small>{{p.plan}}</small></td><td>{{p.cycle}}</td><td>{{p.manager}}</td><td><span :class="['status',statusClass(p.status)]">{{p.status}}</span></td><td>{{p.progress}}%</td><td><button class="link-btn" @click="openProject(p)">查看详情</button></td></tr></tbody></table></div></section>
<section v-else-if="active==='tasks'" class="page"><div class="page-title"><div><p class="eyebrow">OPERATIONS / TASKS</p><h1>任务调度</h1><p class="muted">从计划生成、资源调度到现场执行，全程留痕。</p></div></div><div class="task-banner"><div class="banner-icon"><ClipboardList :size="23"/></div><div><b>主案例任务执行情况</b><span>已完成 {{tasks.filter(t=>t.status==='已完成').length}} 个 · 待处理 {{tasks.filter(t=>t.status!=='已完成').length}} 个</span></div><button class="ghost-light" @click="openTask(tasks[0])">查看任务包 →</button></div><div class="card table-card"><table><thead><tr><th>任务编号</th><th>项目 / 区域</th><th>执行日期</th><th>飞手</th><th>设备</th><th>状态</th><th>资料</th><th></th></tr></thead><tbody><tr v-for="t in tasks" :key="t.id"><td><b class="mono">{{t.id}}</b></td><td>{{t.project}}<small>{{t.area}} · {{t.region}}</small></td><td>{{t.date}}</td><td>{{t.pilot}}</td><td>{{t.drone}}</td><td><span :class="['status',statusClass(t.status)]">{{t.status}}</span></td><td>{{t.files}} / {{t.total}}</td><td><button class="link-btn" @click="openTask(t)">查看任务</button></td></tr></tbody></table></div></section>
<section v-else-if="active==='ai'" class="page"><div class="page-title"><div><p class="eyebrow">INTELLIGENCE / VISION ANALYSIS</p><h1>AI影像分析 <span class="live-dot">● 模拟分析</span></h1><p class="muted">输入为已校验巡检影像，输出候选异常，最终结论由检查人员人工确认。</p></div><button class="secondary" @click="runAnalysis"><ScanSearch :size="17"/> 执行模拟分析</button></div><div class="ai-notice"><Sparkles :size="19"/><div><b>AI辅助识别（Mock）</b><span>识别结果仅作为辅助判断，不替代人工责任判断。</span></div><span class="notice-tag">任务：{{selectedTask.id}}</span></div><div class="ai-layout"><div class="card image-card"><div class="card-title"><div><h3>影像预览</h3><span>{{selectedTask.area}} · {{selectedTask.files}}份已归档资料</span></div></div><div class="inspection-image"><div class="image-sky"></div><div class="solar-field"><i v-for="i in 18" :key="i"></i></div><div class="detect-box box-one"><span>遮挡 · 92%</span></div><div class="detect-box box-two"><span>裂缝 · 88%</span></div><div class="image-overlay"><span>演示影像 · 标注图</span><span>热成像 / RGB</span></div></div></div><div class="card detection-card"><div class="card-title"><div><h3>AI候选结果</h3><span>4个候选问题，等待人工审核</span></div><span class="analysis-done"><Check :size="14"/> 分析完成</span></div><div class="detection-list"><div v-for="i in issues" :key="i.id" class="detection-item" @click="go('issues')"><div :class="['detect-dot',i.color]"><ScanSearch :size="16"/></div><div class="detect-content"><b>{{i.type}}</b><span>{{i.loc}} · {{i.status}}</span></div><strong>{{i.confidence}}</strong></div></div><button class="primary full" @click="go('issues')">进入问题审核 <ArrowUpRight :size="16"/></button></div></div></section>
<section v-else-if="active==='issues'" class="page"><div class="page-title"><div><p class="eyebrow">QUALITY / ISSUE REVIEW</p><h1>问题审核</h1><p class="muted">检查人员对AI候选和人工问题形成可追溯结论。</p></div><button class="secondary" @click="addIssueModal=true"><Plus :size="17"/> 人工新增问题</button></div><div class="issue-summary"><div><span>待审核</span><b>{{pending.length}}</b><small>需要人工确认</small></div><div><span>已确认有效</span><b class="blue-number">{{confirmed.length}}</b><small>进入报告统计</small></div><div><span>误报</span><b>{{issues.filter(i=>i.status==='误报').length}}</b><small>保留审核意见</small></div><div><span>本次AI候选</span><b>4</b><small>来自归档影像</small></div></div><div class="filter-tabs"><button v-for="f in ['全部','待审核','已确认','误报','需复查','人工新增']" :key="f" :class="{selected:issueFilter===f}" @click="issueFilter=f">{{f}}</button></div><div class="card table-card"><table><thead><tr><th>位置</th><th>类型</th><th>时间</th><th>AI结果</th><th>状态</th><th>审核意见</th><th>操作</th></tr></thead><tbody><tr v-for="i in filteredIssues" :key="i.id"><td><b>{{i.loc}}</b><small>{{i.id}} · {{i.taskId}}</small></td><td><span class="type-chip">{{i.type}}</span></td><td>{{i.time}}</td><td><b class="confidence">{{i.confidence}}</b><small> · 模拟AI候选</small></td><td><span :class="['status',statusClass(i.status)]">{{i.status}}</span></td><td><small>{{i.opinion||'待人工判断'}}</small></td><td><div v-if="i.status==='待审核'" class="issue-actions"><button class="icon-action good" @click="updateIssue(i,'已确认')"><Check :size="15"/></button><button class="icon-action bad" @click="updateIssue(i,'误报')"><X :size="15"/></button><button class="icon-action review" @click="updateIssue(i,'需复查')"><RotateCcw :size="15"/></button></div><span v-else class="muted">已处理</span></td></tr></tbody></table></div></section>
<section v-else-if="active==='reports'" class="page"><div class="page-title"><div><p class="eyebrow">DELIVERY / REPORTS</p><h1>报告交付</h1><p class="muted">依据已确认问题生成初稿，经项目负责人审核后模拟交付。</p></div><div class="page-actions"><button class="secondary" @click="showToast('报告预览已打开')"><Eye :size="16"/> 查看报告</button><button class="primary" @click="deliver"><Send :size="16"/> 模拟交付</button></div></div><div class="report-status-line"><span>报告流程</span><b :class="{active:reportStatus==='待负责人审核'}">待负责人审核</b><i>→</i><b :class="{active:['已审核','已交付'].includes(reportStatus)}">已审核</b><i>→</i><b :class="{active:reportStatus==='已交付'}">已交付</b><span class="status-spacer"></span><span :class="['status',statusClass(reportStatus)]">{{reportStatus}}</span></div><div class="report-feature card"><div class="report-cover"><div class="cover-top"><div class="brand-mark"><Plane :size="17"/></div><span>巡检报告 · 2026 / 08 · 演示版本</span></div><div class="cover-title"><span>INSPECTION REPORT</span><h2>华东新能源科技园<br/>一期月度巡检报告</h2><p>专业 · 高效 · 可追溯</p></div><div class="cover-bottom"><span>SKYWISE DIGITAL</span><span>REPORT-20260812-001</span></div></div><div class="report-info"><div class="report-label">报告初稿 / V1.0</div><h2>华东新能源科技园一期<br/>月度无人机巡检报告</h2><p class="muted">报告编号：REPORT-20260812-001 · 数据来源：{{confirmed.length}}个已确认问题</p><div class="report-meta"><span><b>项目客户</b>华东新能源科技有限公司</span><span><b>巡检区域</b>A区 / 组件区01-08</span><span><b>巡检日期</b>2026年8月12日</span><span><b>报告状态</b><em>{{reportStatus}}</em></span><span><b>审核人</b>{{reportStatus==='待负责人审核'?'待项目负责人':'李晨'}}</span><span><b>交付说明</b>{{reportStatus==='已交付'?'已模拟交付并留痕':'审核后可交付'}}</span></div><div v-if="roleKey==='manager'||roleKey==='admin'" class="report-buttons"><button class="primary" @click="reviewReport('已审核')">审核通过 <Check :size="16"/></button><button class="secondary" @click="reviewReport('已退回')">退回修改 <RotateCcw :size="16"/></button></div></div></div><div class="report-stats"><div class="card"><span>归档影像</span><b>{{selectedTask.files}} <small>份</small></b><i>任务级归档</i></div><div class="card"><span>报告问题</span><b>{{confirmed.length}} <small>项</small></b><i class="red-text">依据人工审核结果</i></div><div class="card"><span>报告版本</span><b>{{reportStatus==='已交付'?'V1.1':'V1.0'}}</b><i>{{reportStatus==='已交付'?'已留痕':'等待审核'}}</i></div><div class="card"><span>交付状态</span><b>{{reportStatus}}</b><i>演示状态</i></div></div></section>
<section v-else-if="active==='history'" class="page"><div class="page-title"><div><p class="eyebrow">INSIGHTS / COMPARISON</p><h1>历史对比</h1><p class="muted">以项目区域、巡检时间和任务关联历史影像，支持基础并排对比。</p></div></div><div class="history-head card"><div><span class="eyebrow">对比对象 · 基础关联 Mock</span><h3>A区 / 组件区03（区域编码：A-03）</h3><p class="muted">历史任务 2026-07-12 · 当前任务 {{selectedTask.id}} · 自动配准与趋势预测待确认</p></div><div class="trend-stat"><span>当前已确认问题</span><b>{{confirmed.length}}</b><small>基于两批演示数据的人工观察</small></div></div><div class="compare-grid"><div class="card compare-card"><div class="compare-title"><div><b>历史批次</b><span>2026-07-12 · 历史影像</span></div><span class="old-tag">历史</span></div><div class="compare-image old"><div class="solar-field small-grid"><i v-for="i in 24" :key="i"></i></div><div class="old-mark mark-a"></div></div><div class="compare-foot"><span>发现问题 <b>2</b></span><span>已确认 <b>1</b></span></div></div><div class="compare-arrow">→</div><div class="card compare-card"><div class="compare-title"><div><b>当前批次</b><span>2026-08-12 · 当前影像</span></div><span class="new-tag">当前</span></div><div class="compare-image"><div class="solar-field small-grid"><i v-for="i in 24" :key="i"></i></div><div class="old-mark mark-a"></div><div class="new-mark mark-b"></div><div class="new-mark mark-c"></div></div><div class="compare-foot"><span>发现问题 <b class="red-text">{{issues.length}}</b></span><span>已确认 <b class="red-text">{{confirmed.length}}</b></span></div></div></div><div class="card timeline-card"><div class="card-title"><div><h3>问题变化记录</h3><span>当前仅展示区域/时间关联后的 Mock 观察</span></div></div><div class="history-notes"><div><b>持续：A-03 / 组件排2 / P-017</b><small>历史与当前均有积水候选，需结合人工审核结论观察变化。</small></div><div><b>新增：A-03 / 组件排3 / P-028</b><small>当前批次出现遮挡候选，已进入问题审核。</small></div><div><b>边界：自动配准、趋势预测、整改复检</b><small>方案标记为待确认或后续能力，本期不作为正式结论。</small></div></div></div></section>
<section v-else-if="active==='fleet'" class="page"><div class="page-title"><div><p class="eyebrow">OPERATIONS / FLEET</p><h1>飞手与设备</h1><p class="muted">维护飞手资质、负责区域和无人机设备状态。</p></div></div><div class="fleet-grid"><div class="card table-card"><div class="card-title fleet-card-title"><div><h3>飞手信息</h3><span>资质与负责区域（演示台账）</span></div></div><table><thead><tr><th>姓名</th><th>资质</th><th>区域</th><th>状态</th></tr></thead><tbody><tr v-for="f in [{n:'张伟',l:'高级飞手',a:'华东区域',s:'执行中'},{n:'李浩',l:'中级飞手',a:'苏州园区',s:'空闲'},{n:'赵磊',l:'高级飞手',a:'浦东机场',s:'空闲'}]" :key="f.n"><td>{{f.n}}</td><td>{{f.l}}</td><td>{{f.a}}</td><td>{{f.s}}</td></tr></tbody></table></div><div class="card table-card"><div class="card-title fleet-card-title"><div><h3>无人机设备</h3><span>设备编号与状态（演示台账）</span></div></div><table><thead><tr><th>型号</th><th>设备编号</th><th>状态</th></tr></thead><tbody><tr v-for="d in [{m:'DJI Mavic 3E',id:'DJI-M3E-0068',s:'执行中'},{m:'DJI Mavic 3T',id:'DJI-M3T-0021',s:'空闲'},{m:'DJI Matrice 30T',id:'DJI-M30T-0008',s:'空闲'}]" :key="d.id"><td>{{d.m}}</td><td class="mono">{{d.id}}</td><td>{{d.s}}</td></tr></tbody></table></div></div></section>
</div></main>
<div v-if="toast" class="toast"><Check :size="16"/> {{toast}}</div>
<div v-if="projectDetail" class="modal-mask" @click.self="projectDetail=false"><div class="detail-drawer"><div class="modal-head"><div><span class="eyebrow">PROJECT DETAIL / {{selectedProject.id}}</span><h2>{{selectedProject.name}}</h2><p class="muted">{{selectedProject.client}} · 演示数据</p></div><button class="close" @click="projectDetail=false"><X/></button></div><div class="detail-grid"><div><span>项目状态</span><b><span :class="['status',statusClass(selectedProject.status)]">{{selectedProject.status}}</span></b></div><div><span>巡检周期</span><b>{{selectedProject.cycle}}</b></div><div><span>区域数量</span><b>{{selectedProject.regions}}个</b></div><div><span>项目负责人</span><b>{{selectedProject.manager}}</b></div></div><div class="detail-section"><h3>区域与检查标准</h3><p><MapPin :size="15"/> {{selectedProject.area}}</p><p><ShieldCheck :size="15"/> {{selectedProject.standard}}</p><p><CalendarDays :size="15"/> {{selectedProject.plan}}</p></div><div class="detail-section"><h3>关联任务</h3><div class="related-row" v-for="t in tasks.filter(t=>t.projectId===selectedProject.id)" :key="t.id"><div><b>{{t.id}}</b><small>{{t.area}} · {{t.pilot}} / {{t.drone}}</small></div><span :class="['status',statusClass(t.status)]">{{t.status}}</span></div></div><div class="detail-section"><h3>项目流程与留痕</h3><div class="timeline"><div v-for="l in logs.slice(0,4)" :key="l.time+l.text"><i></i><div><b>{{l.text}}</b><small>{{l.time}} · {{l.role}}</small></div></div></div></div><div class="modal-actions"><button class="secondary" @click="go('history');projectDetail=false"><History :size="15"/> 历史对比</button><button class="primary" @click="go('reports');projectDetail=false"><FileText :size="15"/> 报告交付</button></div></div></div>
<div v-if="taskDetail" class="modal-mask" @click.self="taskDetail=false"><div class="detail-drawer"><div class="modal-head"><div><span class="eyebrow">TASK PACKAGE / {{selectedTask.id}}</span><h2>{{selectedTask.area}}</h2><p class="muted">{{selectedTask.project}} · {{selectedTask.region}} · 演示任务</p></div><button class="close" @click="taskDetail=false"><X/></button></div><div class="task-state-card"><div><span>当前状态</span><b><span :class="['status',statusClass(selectedTask.status)]">{{selectedTask.status}}</span></b></div><div><span>责任人</span><b>{{selectedTask.pilot}}</b></div><div><span>设备</span><b>{{selectedTask.drone}}</b></div><div><span>计划日期</span><b>{{selectedTask.date}}</b></div></div><div class="detail-section"><h3>任务要求</h3><p>{{selectedTask.note}}</p><div class="task-checklist"><span :class="{checked:selectedTask.files>0}"><Check :size="14"/> RGB照片：{{selectedTask.files?'已上传':'待上传'}}</span><span :class="{checked:selectedTask.files>0}"><Check :size="14"/> 热成像资料：{{selectedTask.files?'已上传':'待上传'}}</span><span :class="{checked:selectedTask.files>0}"><Check :size="14"/> 飞行记录：{{selectedTask.files?'已上传':'待上传'}}</span><span><PackageCheck :size="14"/> 资料完整性：{{selectedTask.files}} / {{selectedTask.total}}</span></div></div><div v-if="roleKey==='pilot'&&['待执行','执行中'].includes(selectedTask.status)" class="detail-section"><h3>现场执行</h3><div class="upload-box" @click="uploadFiles"><Upload :size="22"/><b>模拟上传现场资料</b><span>照片 / 视频 / 飞行记录 / 备注</span></div></div><div v-else-if="selectedTask.files" class="detail-section"><h3>资料归档结果</h3><div class="archive-result"><Check :size="19"/><div><b>资料已归档，质量校验通过</b><span>{{selectedTask.files}}份文件已关联至任务</span></div></div></div><div class="modal-actions"><button class="secondary" @click="taskDetail=false">关闭</button><button v-if="roleKey==='pilot'&&selectedTask.status==='待执行'" class="primary" @click="startTask(selectedTask)"><Plane :size="15"/> 开始执行</button><button v-if="selectedTask.files&&selectedTask.status==='待AI分析'" class="primary" @click="runAnalysis();taskDetail=false"><ScanSearch :size="15"/> 执行模拟分析</button></div></div></div>
<div v-if="newProject" class="modal-mask" @click.self="newProject=false"><div class="modal"><div class="modal-head"><div><span class="eyebrow">NEW PROJECT</span><h2>新建巡检项目</h2></div><button class="close" @click="newProject=false"><X/></button></div><label>项目名称</label><div class="input"><FolderKanban :size="17"/><input value="华东新能源科技园二期"/></div><label>客户名称</label><div class="input"><UserRound :size="17"/><input placeholder="请输入客户名称"/></div><p class="modal-note">创建后需继续配置区域、计划和检查标准，才能生成可执行任务。</p><div class="modal-actions"><button class="secondary" @click="newProject=false">取消</button><button class="primary" @click="newProject=false;showToast('项目已创建，请继续配置区域与计划')">创建项目</button></div></div></div>
<div v-if="addIssueModal" class="modal-mask" @click.self="addIssueModal=false"><div class="modal"><div class="modal-head"><div><span class="eyebrow">MANUAL ISSUE</span><h2>人工新增问题</h2></div><button class="close" @click="addIssueModal=false"><X/></button></div><label>问题位置</label><div class="input"><MapPin :size="17"/><input value="A-03 / 组件排4 / P-052"/></div><label>问题描述</label><textarea placeholder="请描述现场发现的问题..."></textarea><div class="modal-actions"><button class="secondary" @click="addIssueModal=false">取消</button><button class="primary" @click="addIssue">创建问题</button></div></div></div>
</div></template>
